repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: mixed-line-ending
        args: [--fix=lf]
        files: '\.sh$|^Dockerfile$|^Makefile$'
      - id: check-ast
        language_version: python3.10
      - id: check-builtin-literals
        language_version: python3.10
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: name-tests-test
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.10
      args:
        - --line-length=120
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
    - id: mypy
      language_version: python3.10
      args: [--ignore-missing-imports]
      additional_dependencies: [ types-PyYAML==6.0.8 ]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    - id: isort
      language_version: python3.10
      args: ["--profile", "black"]
